name: Docker

on:
  workflow_dispatch:
    inputs:
      streamlink_version:
        description: Streamlink version
        required: true
      latest:
        type: boolean
        description: Tag as latest?

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: |
            linux/amd64
            linux/arm/v6
            linux/arm/v7
          push: true
          build-args: |
            STREAMLINK_VERSION=${{ github.event.inputs.streamlink_version }}
          tags: |
            jensforstmann/streamlink:${{ github.event.inputs.streamlink_version }}
            ${{ github.event.inputs.latest == 'true' && 'jensforstmann/streamlink:latest' || '' }}
